### ISSUE TITLE
disnake понос !!!

### ISSUE THREAD

**Issue by MCausc78** [darkness800/QuickAI#3]
discord.py не понос, ему 9 лет!

**Comment by infernox-dev** [comment]
Respect, sigma moment

**Comment by darkness800** [comment]
Похуй мне

**Comment by darkness800** [comment]
> discord.py не понос, ему 9 лет!

Ебнутый, на чем удобно на том и пишу

**Comment by darkness800** [comment]
> Уважение, сигма-момент

Сказал юзер диснейка

**Comment by infernox-dev** [comment]
Я на дискорд.пу переписываю спейсаи

**Comment by infernox-dev** [comment]
Макакус

**Comment by darkness800** [comment]
> Макакус

Ок, ичо?

**Comment by darkness800** [comment]
> > Макакус
> 
> Ок, ичо?

Две совершенно одинаковых библы

**Comment by infernox-dev** [comment]
> > > Макакус
> > 
> > 
> > Ок, ичо?
> 
> Две совершенно одинаковых библы

Они разные гениус

**Comment by darkness800** [comment]
> > > > Макакус
> > > 
> > > 
> > > Ок, ичо?
> > 
> > 
> > Две совершенно одинаковых библы
> 
> Они разные гениус

Там почти ничо кроме интеракций не отличается
